---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: gui-mapping
spec:
  hostname: "*"
  prefix: /faces/
  service: faces-gui.faces
  rewrite: /
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-mapping
spec:
  hostname: "*"
  prefix: /quote/
  service: quote.faces
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: shape-mapping
spec:
  hostname: "*"
  prefix: /shape/
  service: shape.faces
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: smiley-mapping
spec:
  hostname: "*"
  prefix: /smiley/
  service: smiley.faces
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: color-mapping
spec:
  hostname: "*"
  prefix: /color/
  service: color.faces
  timeout_ms: 0
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: face-mapping
spec:
  hostname: "*"
  prefix: /face/
  service: face.faces
  timeout_ms: 0
