---
apiVersion: v1
kind: Service
metadata:
  name: color
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    service: color
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: color
  template:
    metadata:
      labels:
        service: color
    spec:
      containers:
      - name: color
        image: {{ include "partials.color-image" . }}
        imagePullPolicy: {{ include "partials.color-imagePullPolicy" . }}
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: FACES_SERVICE
          value: "color"
        {{- if .Values.color.color }}
        - name: COLOR
          value: {{ .Values.color.color }}
        {{- end -}}
        {{- include "partials.color-errorFraction" . }}
        {{- include "partials.color-delayBuckets" . }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
